### ISSUE TITLE
[Task] Clean up workflows

### ISSUE THREAD

**Issue by al-kau** [Eppie-io/Eppie-App#343]
### Description

Remove the branch **feature/296-upgrading-to-uno-platform-5** in workflow files from events **pull_request** and **push** after #324

```yaml
  push:
    branches:
      - main
      - release/**
      - feature/296-upgrading-to-uno-platform-5 # temporarily
  pull_request:
    branches:
      - main
      - release/**
      - feature/296-upgrading-to-uno-platform-5 # temporarily
```
### Subtasks

- [ ] `.github/workflows/build.yml` workflow
- [ ] `.github/workflows/format.yml` workflow
